[package]
name = "rdxsort"
version = "0.1.0"
authors = ["Marco Neumann <marco@crepererum.net>"]
license = "MIT"
repository = "https://github.com/crepererum/rdxsort-rs.git"

[dev-dependencies]
rand = "0.3"
